pages:
  stage: deploy
  script:
    - python3 build.py
    - convert context.downloadit/icon.png -define icon:auto-resize=16,24,32,48,64,72,96,128,256 public/favicon.ico
  artifacts:
    paths:
      - public
  only:
    - master
